

(package! whole-line-or-region)
(package! afternoon-theme)
(package! helm-ag)
(package! iflipb)
(package! auto-highlight-symbol)
(package! helm-swoop)
(package! w3m)
(package! zoom-window)
(package! undo-tree)
(package! protobuf-mode)
(package! fastnav)
(package! git-link)
(package! backward-forward)
(package! hl-line)
;;(mode! auto-dim-other-buffers)
