(package! helm)
(package! compile+)
(package! grep+)
(package! whole-line-or-region)  ;; what is this?
(package! afternoon-theme)
(package! helm-ag)
(package! helm-swoop)
(package! undo-tree)
(package! protobuf-mode)
(package! fastnav)
(package! git-link)
(package! hl-line)
(package! doom-modeline)
(package! package-lint)
(package! ace-window)
(package! move-text)
(package! anzu)
(package! symbol-navigation-hydra)
